import Head from 'next/head'
import { Header } from '../components/Header';
import Canvas from '../components/Canvas';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <div className="flex flex-col w-screen h-screen">
          <Header />
          {/* container */}
          <div className="flex flex-row justify-center ...">
            <Canvas />
          </div>
          <div className="flex flex-row justify-center">
            <button className="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded">
              前の画像へ
            </button>
            <button className="ml-2 bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded">
              次の画像へ
            </button>
          </div>
        </div>
      </div>
    </div>
  )
}
