import Head from 'next/head'
import Image from 'next/image'
import styles from './styles/Home.module.css'
import { Header } from '../components/Header';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <div className="flex flex-col w-screen h-screen">
          <Header />
          {/* container */}
          <div className="flex flex-row grow">
              {/* content */}
              {/* <Canvas className="h-screen">
              </Canvas> */}
          </div>
        </div>
      </div>
    </div>
  )
}
